name: Create an issue on update README.md

on: 
  push:
    branches:
      - master
    paths: 
      - 'README.md'

jobs:
  stuff:
    steps:
      - uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: hoxo-m
          filename: .github/create-an-issue-template.md
